version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
        - backend
volumes:
  data:
  logs:
          